export const ActionTypes = {
    ADD_CART_PRODUCT: "ADD_CART_PRODUCT",
    ADD_SAVE_PRODUCT: "ADD_SAVE_PRODUCT",
    ADD_COUNT_PRODUCT: "ADD_COUNT_PRODUCT",
    CHOOSE_CATEGORY_ID: "CHOOSE_CATEGORY_ID",
}